import { Nivo } from "@prisma/client";

export type SeedLesson = {
  title: string;
  nivo: Nivo;
};

export const initialLessons: SeedLesson[] = [
  // Nivo 1
  { title: "Euzubillah i Bismillah", nivo: Nivo.First },
  { title: "Rabbi jessir", nivo: Nivo.First },
  { title: "Kelime i šehadet", nivo: Nivo.First },
  { title: "Čistoća", nivo: Nivo.First },
  { title: "Abdest", nivo: Nivo.First },
  { title: "Subhaneke", nivo: Nivo.First },
  { title: "Sure El-Fatiha", nivo: Nivo.First },
  { title: "Šta je islam", nivo: Nivo.First },
  { title: "Islamski šarti", nivo: Nivo.First },
  { title: "Selam", nivo: Nivo.First },
  { title: "Ko je naš uzor", nivo: Nivo.First },
  { title: "Sura En-Nas", nivo: Nivo.First },
  { title: "Sura El-Felek", nivo: Nivo.First },
  { title: "Mekteb, šta je to?", nivo: Nivo.First },
  { title: "Kako jedemo", nivo: Nivo.First },
  { title: "Sura El-Ihlas", nivo: Nivo.First },

  // Nivo 2
  { title: "Imanski šarti", nivo: Nivo.Second },
  { title: "Namaski šarti", nivo: Nivo.Second },
  { title: "Namaski rukni", nivo: Nivo.Second },
  { title: "Akšam-namaz", nivo: Nivo.Second },
  { title: "Ettehijjatu", nivo: Nivo.Second },
  { title: "Salavati", nivo: Nivo.Second },
  { title: "Dova", nivo: Nivo.Second },
  { title: "Muhammed alejhis-selam", nivo: Nivo.Second },
  { title: "Farz i sunnet", nivo: Nivo.Second },
  { title: "Sura El-Leheb", nivo: Nivo.Second },
  { title: "Halal i haram", nivo: Nivo.Second },
  { title: "Isa alejhis-selam", nivo: Nivo.Second },
  { title: "Sura En-Nasr", nivo: Nivo.Second },
  { title: "Kur'an", nivo: Nivo.Second },
  { title: "Meleki", nivo: Nivo.Second },
  { title: "Sura El-Kevser", nivo: Nivo.Second },

  // Nivo 3
  { title: "Blagdani muslimana", nivo: Nivo.Third },
  { title: "Mubarek noći i drugi značajni datumi", nivo: Nivo.Third },
  { title: "Ezan", nivo: Nivo.Third },
  { title: "Ikamet", nivo: Nivo.Third },
  { title: "Sabah-namaz", nivo: Nivo.Third },
  { title: "Šta kvari abdest?", nivo: Nivo.Third },
  { title: "Podne-namaz", nivo: Nivo.Third },
  { title: "Ikindija-namaz", nivo: Nivo.Third },
  { title: "Ramazanski post", nivo: Nivo.Third },
  { title: "Zekat-sadaka", nivo: Nivo.Third },
  { title: "Sura El-Kafirun", nivo: Nivo.Third },
  { title: "Jacija-namaz", nivo: Nivo.Third },
  { title: "Vitr-namaz", nivo: Nivo.Third },
  { title: "Božije knjige", nivo: Nivo.Third },
  { title: "Ve Kutubihi", nivo: Nivo.Third },
  { title: "Božiji poslanici", nivo: Nivo.Third },
  { title: "Ve Rusulihi", nivo: Nivo.Third },
  { title: "Adem alejhis-selam", nivo: Nivo.Third },
  { title: "Nuh alejhis-selam", nivo: Nivo.Third },
  { title: "Hadž", nivo: Nivo.Third },
  { title: "Sura El-Ma'un", nivo: Nivo.Third },

  // Nivo 4
  { title: "Esmau-l-husna, Allahova lijepa imena", nivo: Nivo.Fourth },
  { title: "Ibrahim alejhis-selam", nivo: Nivo.Fourth },
  { title: "Porodica u islamu", nivo: Nivo.Fourth },
  { title: "Poslanikova a.s porodica i ashabi", nivo: Nivo.Fourth },
  { title: "Prijateljstvo", nivo: Nivo.Fourth },
  { title: "Sura El-Kard", nivo: Nivo.Fourth },
  { title: "Musa alejhis-selam", nivo: Nivo.Fourth },
  { title: "Mudžize", nivo: Nivo.Fourth },
  { title: "Vrijednost učenja", nivo: Nivo.Fourth },
  { title: "Džuma-namaz", nivo: Nivo.Fourth },
  { title: "Teravih-namaz", nivo: Nivo.Fourth },
  { title: "Dženaza i Bajram-namaz", nivo: Nivo.Fourth },
  { title: "Radnje koje kvare namaz", nivo: Nivo.Fourth },
  { title: "Radnje koje kvare abdest", nivo: Nivo.Fourth },
  { title: "Zikr i dova poslije namaza", nivo: Nivo.Fourth },
  { title: "Važnost džemata i džamije", nivo: Nivo.Fourth },
  { title: "Naklanjavanje propuštenih namaza", nivo: Nivo.Fourth },
  { title: "Sura 'Asr", nivo: Nivo.Fourth },
  { title: "Gusul", nivo: Nivo.Fourth },
  { title: "Tejemmum", nivo: Nivo.Fourth },

  // Nivo 5
  { title: "Osnovi nauke tefsira", nivo: Nivo.Fifth },
  { title: "Sifati, Allahova svojstva", nivo: Nivo.Fifth },
  { title: "El-Bekara, 1-5", nivo: Nivo.Fifth },
  { title: "El-Bekara, 285. i 286.", nivo: Nivo.Fifth },
  { title: "Sura El-Fil", nivo: Nivo.Fifth },
  { title: "Sura Kurejš", nivo: Nivo.Fifth },
  { title: "Kunut-dova", nivo: Nivo.Fifth },
  { title: "Vjerovanje u sudnji dan", nivo: Nivo.Fifth },
  { title: "Vjerovanje u Božije određenje", nivo: Nivo.Fifth },
  { title: "Osnovi nauke hadisa", nivo: Nivo.Fifth },
  { title: "Četvorica pravednih halifa", nivo: Nivo.Fifth },
  { title: "Širenje islama", nivo: Nivo.Fifth },
  { title: "Namaski vadžibi", nivo: Nivo.Fifth },
  { title: "Sehvi-sedžda", nivo: Nivo.Fifth },
  { title: "Namaz musafira", nivo: Nivo.Fifth },
  { title: "Prispijevanje u džemat", nivo: Nivo.Fifth },
  { title: "Nafila-namazi (dobrovoljni namazi)", nivo: Nivo.Fifth },
  { title: "Islam u Bosni i Hercegovoni", nivo: Nivo.Fifth },
  { title: "Islam u Švedskoj", nivo: Nivo.Fifth },
  { title: "Agresija na BiH", nivo: Nivo.Fifth },
  { title: "Osnovi šerijatskog bračnog prava", nivo: Nivo.Fifth },
];
