export type SeedLesson = {
  title: string;
  nivo: number;
};

export const initialLessons: SeedLesson[] = [
  // Nivo 1
  { title: "Euzubillah i Bismillah", nivo: 1 },
  { title: "Rabbi jessir", nivo: 1 },
  { title: "Kelime i šehadet", nivo: 1 },
  { title: "Čistoća", nivo: 1 },
  { title: "Abdest", nivo: 1 },
  { title: "Subhaneke", nivo: 1 },
  { title: "Sure El-Fatiha", nivo: 1 },
  { title: "Šta je islam", nivo: 1 },
  { title: "Islamski šarti", nivo: 1 },
  { title: "Selam", nivo: 1 },
  { title: "Ko je naš uzor", nivo: 1 },
  { title: "Sura En-Nas", nivo: 1 },
  { title: "Sura El-Felek", nivo: 1 },
  { title: "Mekteb, šta je to?", nivo: 1 },
  { title: "Kako jedemo", nivo: 1 },
  { title: "Sura El-Ihlas", nivo: 1 },

  // Nivo 2
  { title: "Imanski šarti", nivo: 2 },
  { title: "Namaski šarti", nivo: 2 },
  { title: "Namaski rukni", nivo: 2 },
  { title: "Akšam-namaz", nivo: 2 },
  { title: "Ettehijjatu", nivo: 2 },
  { title: "Salavati", nivo: 2 },
  { title: "Dova", nivo: 2 },
  { title: "Muhammed alejhis-selam", nivo: 2 },
  { title: "Farz i sunnet", nivo: 2 },
  { title: "Sura El-Leheb", nivo: 2 },
  { title: "Halal i haram", nivo: 2 },
  { title: "Isa alejhis-selam", nivo: 2 },
  { title: "Sura En-Nasr", nivo: 2 },
  { title: "Kur'an", nivo: 2 },
  { title: "Meleki", nivo: 2 },
  { title: "Sura El-Kevser", nivo: 2 },

  // Nivo 3
  { title: "Blagdani muslimana", nivo: 3 },
  { title: "Mubarek noći i drugi značajni datumi", nivo: 3 },
  { title: "Ezan", nivo: 3 },
  { title: "Ikamet", nivo: 3 },
  { title: "Sabah-namaz", nivo: 3 },
  { title: "Šta kvari abdest?", nivo: 3 },
  { title: "Podne-namaz", nivo: 3 },
  { title: "Ikindija-namaz", nivo: 3 },
  { title: "Ramazanski post", nivo: 3 },
  { title: "Zekat-sadaka", nivo: 3 },
  { title: "Sura El-Kafirun", nivo: 3 },
  { title: "Jacija-namaz", nivo: 3 },
  { title: "Vitr-namaz", nivo: 3 },
  { title: "Božije knjige", nivo: 3 },
  { title: "Ve Kutubihi", nivo: 3 },
  { title: "Božiji poslanici", nivo: 3 },
  { title: "Ve Rusulihi", nivo: 3 },
  { title: "Adem alejhis-selam", nivo: 3 },
  { title: "Nuh alejhis-selam", nivo: 3 },
  { title: "Hadž", nivo: 3 },
  { title: "Sura El-Ma'un", nivo: 3 },

  // Nivo 4
  { title: "Esmau-l-husna, Allahova lijepa imena", nivo: 4 },
  { title: "Ibrahim alejhis-selam", nivo: 4 },
  { title: "Porodica u islamu", nivo: 4 },
  { title: "Poslanikova a.s porodica i ashabi", nivo: 4 },
  { title: "Prijateljstvo", nivo: 4 },
  { title: "Sura El-Kard", nivo: 4 },
  { title: "Musa alejhis-selam", nivo: 4 },
  { title: "Mudžize", nivo: 4 },
  { title: "Vrijednost učenja", nivo: 4 },
  { title: "Džuma-namaz", nivo: 4 },
  { title: "Teravih-namaz", nivo: 4 },
  { title: "Dženaza i Bajram-namaz", nivo: 4 },
  { title: "Radnje koje kvare namaz", nivo: 4 },
  { title: "Radnje koje kvare abdest", nivo: 4 },
  { title: "Zikr i dova poslije namaza", nivo: 4 },
  { title: "Važnost džemata i džamije", nivo: 4 },
  { title: "Naklanjavanje propuštenih namaza", nivo: 4 },
  { title: "Sura 'Asr", nivo: 4 },
  { title: "Gusul", nivo: 4 },
  { title: "Tejemmum", nivo: 4 },

  // Nivo 5
  { title: "Osnovi nauke tefsira", nivo: 5 },
  { title: "Sifati, Allahova svojstva", nivo: 5 },
  { title: "El-Bekara, 1-5", nivo: 5 },
  { title: "El-Bekara, 285. i 286.", nivo: 5 },
  { title: "Sura El-Fil", nivo: 5 },
  { title: "Sura Kurejš", nivo: 5 },
  { title: "Kunut-dova", nivo: 5 },
  { title: "Vjerovanje u sudnji dan", nivo: 5 },
  { title: "Vjerovanje u Božije određenje", nivo: 5 },
  { title: "Osnovi nauke hadisa", nivo: 5 },
  { title: "Četvorica pravednih halifa", nivo: 5 },
  { title: "Širenje islama", nivo: 5 },
  { title: "Namaski vadžibi", nivo: 5 },
  { title: "Sehvi-sedžda", nivo: 5 },
  { title: "Namaz musafira", nivo: 5 },
  { title: "Prispijevanje u džemat", nivo: 5 },
  { title: "Nafila-namazi (dobrovoljni namazi)", nivo: 5 },
  { title: "Islam u Bosni i Hercegovoni", nivo: 5 },
  { title: "Islam u Švedskoj", nivo: 5 },
  { title: "Agresija na BiH", nivo: 5 },
  { title: "Osnovi šerijatskog bračnog prava", nivo: 5 },
];
