export const DEFAULT_DIPLOMA_TEMPLATE_PUBLIC_PATH = "/diplomas/default.pdf";
export const DEFAULT_DIPLOMA_TEMPLATE_FILENAME = "default.pdf";

export const DIPLOMA_TEMPLATE_ERR_DEFAULT_ASSET = "DIPLOMA_TEMPLATE_DEFAULT_ASSET_MISSING";
export const DIPLOMA_TEMPLATE_ERR_CUSTOM_NOT_FOUND = "DIPLOMA_TEMPLATE_CUSTOM_NOT_FOUND";
