-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ABSENCE_COMMENT_ADDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HOMEWORK_COMPLETED';
